### PR TITLE
keep track with master

### PR DESCRIPTION
**Pull request by UrsZeidler**

### CODE REVIEW

**Comment by UrsZeidler** [comment]
sorry, wanted to merge yours into mine, not the other way
greetings

**Comment by adridadou** [comment]
no problem :) How is your project going? If you have seen other issues with the StandaloneBlockchain or the PrivateMiner one please let me know (have you seen the new PrivateMiner node to make integration tests?)

**Comment by UrsZeidler** [comment]
I had some time yesterday. Hopefully I will come back to it later this week.

I had some issues with the rcp part and will dig into it when I get the time.
Cool progress on your site, nice to see.

**Comment by adridadou** [comment]
Thanks! 
You have issues with RPC? Feel free to create issues when something doesn't work well. 
Just tell me which node do you use. Geth? Parity? Harmony? Which version?

Good luck

**Comment by UrsZeidler** [comment]
I use the current geth version (geth-linux-amd64-1.5.4-b70acf3c).

**Comment by adridadou** [comment]
Can you create an issue with:
- The node version (what you just saîd now)
- A short description of your issue
- If possible, some code to reproduce it

I will try to make it work ASAP

**Pull request closed without merging**
